# Generated by Django 6.0.6 on 2026-07-14 12:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DerivAccount',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('login_id', models.CharField(max_length=50, unique=True)),
                ('deriv_user_id', models.CharField(db_index=True, max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('currency', models.CharField(max_length=10)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('landing_company', models.CharField(blank=True, max_length=100)),
                ('is_virtual', models.BooleanField(default=False)),
                ('is_connected', models.BooleanField(default=True)),
                ('access_token', models.TextField()),
                ('token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('last_synced', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'deriv_accounts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DerivOAuthSession',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('state', models.CharField(max_length=255, unique=True)),
                ('code_verifier', models.TextField()),
                ('expires_at', models.DateTimeField()),
                ('used', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'deriv_oauth_sessions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TradingSession',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_id', models.CharField(max_length=255, unique=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('connected_at', models.DateTimeField(auto_now_add=True)),
                ('disconnected_at', models.DateTimeField(blank=True, null=True)),
                ('last_activity', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('deriv_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='deriv.derivaccount')),
            ],
            options={
                'db_table': 'deriv_trading_sessions',
                'ordering': ['-connected_at'],
            },
        ),
    ]
