# Generated by Django 6.0.6 on 2026-07-14 17:15

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deriv', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DerivConnection',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('access_token', models.TextField()),
                ('token_type', models.CharField(default='Bearer', max_length=20)),
                ('scopes', models.CharField(blank=True, max_length=255)),
                ('token_expires_at', models.DateTimeField()),
                ('is_connected', models.BooleanField(default=True)),
                ('connected_at', models.DateTimeField(auto_now_add=True)),
                ('disconnected_at', models.DateTimeField(blank=True, null=True)),
                ('last_synced', models.DateTimeField(blank=True, null=True)),
                ('raw_token', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='tradingsession',
            name='deriv_account',
        ),
        migrations.CreateModel(
            name='DerivTradingAccount',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('account_id', models.CharField(max_length=50, unique=True)),
                ('account_type', models.CharField(max_length=20)),
                ('currency', models.CharField(max_length=10)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=20)),
                ('group', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=30)),
                ('raw_data', models.JSONField(blank=True, default=dict)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='deriv.derivconnection')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='DerivAccount',
        ),
        migrations.DeleteModel(
            name='TradingSession',
        ),
    ]
