# Generated by Django 6.0.6 on 2026-06-27 16:15

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('transactions', '0002_alter_transaction_transaction_type'),
        ('wallets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=300, unique=True)),
                ('description', models.TextField()),
                ('campaign_type', models.CharField(choices=[('share', 'Share'), ('click', 'Click'), ('download', 'Download'), ('signup', 'Sign Up'), ('survey', 'Survey'), ('video', 'Video'), ('custom', 'Custom')], max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending_review', 'Pending Review'), ('active', 'Active'), ('paused', 'Paused'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='draft', max_length=30)),
                ('visibility', models.CharField(choices=[('public', 'Public'), ('private', 'Private'), ('invite_only', 'Invite Only')], default='public', max_length=20)),
                ('budget', models.DecimalField(decimal_places=8, default=Decimal('0'), max_digits=20)),
                ('remaining_budget', models.DecimalField(decimal_places=8, default=Decimal('0'), max_digits=20)),
                ('reward_per_action', models.DecimalField(decimal_places=8, default=Decimal('0'), max_digits=20)),
                ('currency', models.CharField(default='Z', max_length=10)),
                ('max_participants', models.PositiveIntegerField(default=0)),
                ('current_participants', models.PositiveIntegerField(default=0)),
                ('requires_verification', models.BooleanField(default=True)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sponsor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='campaigns', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CampaignFunding',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('funding_type', models.CharField(choices=[('initial', 'Initial Funding'), ('top_up', 'Top Up'), ('refund', 'Refund'), ('adjustment', 'Adjustment')], default='initial', max_length=20)),
                ('amount', models.DecimalField(decimal_places=8, max_digits=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='funding_events', to='campaigns.campaign')),
                ('sponsor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='campaign_funding', to=settings.AUTH_USER_MODEL)),
                ('transaction', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='campaign_funding', to='transactions.transaction')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='campaign_funding', to='wallets.wallet')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CampaignMedia',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('file', 'File')], max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='campaigns/images/')),
                ('video', models.FileField(blank=True, null=True, upload_to='campaigns/videos/')),
                ('file', models.FileField(blank=True, null=True, upload_to='campaigns/files/')),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='campaigns.campaign')),
            ],
            options={
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='CampaignParticipation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('joined', 'Joined'), ('in_progress', 'In Progress'), ('submitted', 'Submitted'), ('verified', 'Verified'), ('rejected', 'Rejected'), ('rewarded', 'Rewarded')], default='joined', max_length=20)),
                ('reward_paid', models.BooleanField(default=False)),
                ('reward_amount', models.DecimalField(decimal_places=8, default=Decimal('0'), max_digits=20)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='campaigns.campaign')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='campaign_participations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CampaignReward',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=8, max_digits=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('participation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reward', to='campaigns.campaignparticipation')),
                ('transaction', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='campaign_reward', to='transactions.transaction')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='campaign_rewards', to='wallets.wallet')),
            ],
        ),
        migrations.CreateModel(
            name='CampaignTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('task_type', models.CharField(choices=[('share', 'Share'), ('visit', 'Visit'), ('click', 'Click'), ('watch', 'Watch'), ('download', 'Download'), ('signup', 'Sign Up'), ('referral', 'Referral'), ('manual', 'Manual')], max_length=20)),
                ('reward', models.DecimalField(decimal_places=8, default=Decimal('0'), max_digits=20)),
                ('verification_type', models.CharField(choices=[('automatic', 'Automatic'), ('manual', 'Manual'), ('hybrid', 'Hybrid')], default='manual', max_length=20)),
                ('max_completions', models.PositiveIntegerField(default=1)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='campaigns.campaign')),
            ],
        ),
        migrations.CreateModel(
            name='CampaignSubmission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('proof_url', models.URLField(blank=True, null=True)),
                ('proof_image', models.ImageField(blank=True, null=True, upload_to='campaigns/proofs/')),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('participation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='campaigns.campaignparticipation')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_campaign_submissions', to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='campaigns.campaigntask')),
            ],
        ),
        migrations.AddIndex(
            model_name='campaign',
            index=models.Index(fields=['status'], name='campaigns_c_status_96cb56_idx'),
        ),
        migrations.AddIndex(
            model_name='campaign',
            index=models.Index(fields=['campaign_type'], name='campaigns_c_campaig_ff160b_idx'),
        ),
        migrations.AddIndex(
            model_name='campaign',
            index=models.Index(fields=['visibility'], name='campaigns_c_visibil_48ec4f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='campaignparticipation',
            unique_together={('campaign', 'user')},
        ),
    ]
