# Generated by Django 6.0.6 on 2026-06-27 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('deposit', 'Deposit'), ('withdrawal', 'Withdrawal'), ('transfer', 'Transfer'), ('reward', 'Reward'), ('market_payout', 'Market Payout'), ('campaign_funding', 'Campaign Funding'), ('campaign_reward', 'Campaign Reward'), ('refund', 'Refund')], max_length=32),
        ),
    ]
